### ISSUE TITLE
Env Variables

### ISSUE THREAD

**Issue by xyntechx** [weihong0827/Telegram_Bot_Tutorial#1]
Hi! I think you should use environment variables to store Tokens, URLs, and other sensitive and private information :)

**Comment by weihong0827** [comment]
Yes definitely but considering this is a tutorial that most of the attendees don't even have programming backgrounds it's fair enough to leave the env part out. Since I do not want to overload them with information. the tokens included here are not really very crucial so I think it's fine to leave it. I will bring this point up to the attendees too! thanks for reminding

**Comment by xyntechx** [comment]
Awesome! No worries and thanks :D
